# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1417/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1417/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/conte/Desktop/Lezioni/PACS/Practicas/PACS-P3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/conte/Desktop/Lezioni/PACS/Practicas/PACS-P3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1417/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1417/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/conte/Desktop/Lezioni/PACS/Practicas/PACS-P3/CMakeFiles /home/conte/Desktop/Lezioni/PACS/Practicas/PACS-P3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/conte/Desktop/Lezioni/PACS/Practicas/PACS-P3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pi_taylor_sequential

# Build rule for target.
pi_taylor_sequential: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pi_taylor_sequential
.PHONY : pi_taylor_sequential

# fast build rule for target.
pi_taylor_sequential/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_sequential.dir/build.make CMakeFiles/pi_taylor_sequential.dir/build
.PHONY : pi_taylor_sequential/fast

#=============================================================================
# Target rules for targets named pi_taylor_parallel

# Build rule for target.
pi_taylor_parallel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pi_taylor_parallel
.PHONY : pi_taylor_parallel

# fast build rule for target.
pi_taylor_parallel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_parallel.dir/build.make CMakeFiles/pi_taylor_parallel.dir/build
.PHONY : pi_taylor_parallel/fast

#=============================================================================
# Target rules for targets named pi_taylor_parallel_kahan

# Build rule for target.
pi_taylor_parallel_kahan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pi_taylor_parallel_kahan
.PHONY : pi_taylor_parallel_kahan

# fast build rule for target.
pi_taylor_parallel_kahan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_parallel_kahan.dir/build.make CMakeFiles/pi_taylor_parallel_kahan.dir/build
.PHONY : pi_taylor_parallel_kahan/fast

src/pi_taylor_parallel.o: src/pi_taylor_parallel.cc.o
.PHONY : src/pi_taylor_parallel.o

# target to build an object file
src/pi_taylor_parallel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_parallel.dir/build.make CMakeFiles/pi_taylor_parallel.dir/src/pi_taylor_parallel.cc.o
.PHONY : src/pi_taylor_parallel.cc.o

src/pi_taylor_parallel.i: src/pi_taylor_parallel.cc.i
.PHONY : src/pi_taylor_parallel.i

# target to preprocess a source file
src/pi_taylor_parallel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_parallel.dir/build.make CMakeFiles/pi_taylor_parallel.dir/src/pi_taylor_parallel.cc.i
.PHONY : src/pi_taylor_parallel.cc.i

src/pi_taylor_parallel.s: src/pi_taylor_parallel.cc.s
.PHONY : src/pi_taylor_parallel.s

# target to generate assembly for a file
src/pi_taylor_parallel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_parallel.dir/build.make CMakeFiles/pi_taylor_parallel.dir/src/pi_taylor_parallel.cc.s
.PHONY : src/pi_taylor_parallel.cc.s

src/pi_taylor_parallel_kahan.o: src/pi_taylor_parallel_kahan.cc.o
.PHONY : src/pi_taylor_parallel_kahan.o

# target to build an object file
src/pi_taylor_parallel_kahan.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_parallel_kahan.dir/build.make CMakeFiles/pi_taylor_parallel_kahan.dir/src/pi_taylor_parallel_kahan.cc.o
.PHONY : src/pi_taylor_parallel_kahan.cc.o

src/pi_taylor_parallel_kahan.i: src/pi_taylor_parallel_kahan.cc.i
.PHONY : src/pi_taylor_parallel_kahan.i

# target to preprocess a source file
src/pi_taylor_parallel_kahan.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_parallel_kahan.dir/build.make CMakeFiles/pi_taylor_parallel_kahan.dir/src/pi_taylor_parallel_kahan.cc.i
.PHONY : src/pi_taylor_parallel_kahan.cc.i

src/pi_taylor_parallel_kahan.s: src/pi_taylor_parallel_kahan.cc.s
.PHONY : src/pi_taylor_parallel_kahan.s

# target to generate assembly for a file
src/pi_taylor_parallel_kahan.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_parallel_kahan.dir/build.make CMakeFiles/pi_taylor_parallel_kahan.dir/src/pi_taylor_parallel_kahan.cc.s
.PHONY : src/pi_taylor_parallel_kahan.cc.s

src/pi_taylor_sequential.o: src/pi_taylor_sequential.cc.o
.PHONY : src/pi_taylor_sequential.o

# target to build an object file
src/pi_taylor_sequential.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_sequential.dir/build.make CMakeFiles/pi_taylor_sequential.dir/src/pi_taylor_sequential.cc.o
.PHONY : src/pi_taylor_sequential.cc.o

src/pi_taylor_sequential.i: src/pi_taylor_sequential.cc.i
.PHONY : src/pi_taylor_sequential.i

# target to preprocess a source file
src/pi_taylor_sequential.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_sequential.dir/build.make CMakeFiles/pi_taylor_sequential.dir/src/pi_taylor_sequential.cc.i
.PHONY : src/pi_taylor_sequential.cc.i

src/pi_taylor_sequential.s: src/pi_taylor_sequential.cc.s
.PHONY : src/pi_taylor_sequential.s

# target to generate assembly for a file
src/pi_taylor_sequential.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_taylor_sequential.dir/build.make CMakeFiles/pi_taylor_sequential.dir/src/pi_taylor_sequential.cc.s
.PHONY : src/pi_taylor_sequential.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pi_taylor_parallel"
	@echo "... pi_taylor_parallel_kahan"
	@echo "... pi_taylor_sequential"
	@echo "... src/pi_taylor_parallel.o"
	@echo "... src/pi_taylor_parallel.i"
	@echo "... src/pi_taylor_parallel.s"
	@echo "... src/pi_taylor_parallel_kahan.o"
	@echo "... src/pi_taylor_parallel_kahan.i"
	@echo "... src/pi_taylor_parallel_kahan.s"
	@echo "... src/pi_taylor_sequential.o"
	@echo "... src/pi_taylor_sequential.i"
	@echo "... src/pi_taylor_sequential.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

